---
Resources:
  
  # Our EC2 instance 
  CustomEC2Instance: 
     Type: AWS::EC2::Instance
     Properties:
      ImageId: ami-a4c7edb2
      AvailabilityZone: us-east-1a
      InstanceType:  !Ref InstanceType
      Tags: 
        - Key: Name
          Value: My-First-Template
  
  # Custom S3 Bucket
  CustomS3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !Sub "${AWS::Region}-${AWS::AccountId}-1"
      AccessControl: PublicRead

  # Custom SNS Topic
  CustomMySNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: !Ref AlarmEMail
          Protocol: email
      TopicName: !Ref SampleTopic


# CloudFormation Parameters
Parameters:
  
  # Email address for SNS Notification 
  AlarmEMail:
    Description: EMail address to notify if there are any operational issues
    Type: String
    Default: eechukwu@gmail.com
    AllowedPattern: >-
      ([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)
    ConstraintDescription: must be a valid email address.

  # Enter your SNS Topic Here 
  SampleTopic:
    Description: Enter an SNS Topic Here, Please no space allowed
    Type: String
    Default: CloudFormationPractise

  # Type of instance
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.small
    AllowedValues:
      - t1.micro
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium
    ConstraintDescription: must be a valid EC2 instance type.