AWSTemplateFormatVersion: 2010-09-09
Description: >-
  CloudFormation Template to create admin user, groups, policies and access keys 
  created by Emmanuel C during cloud formation practise 


Resources:
  
  # Create an Admin user, we are referencing the Password feild defined in the parameter section of our template
  MyCFUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName : !Ref Username
      LoginProfile:
        Password: !Ref Password

  MyAdminUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName : !Ref AdminUsername
      LoginProfile:
        Password: !Ref AdminPassword
  

  # Create our User Group
  MyCFUserGroup:
    Type: 'AWS::IAM::Group'
    Properties:
      GroupName: devops-team
  
  # Create our Admin Group
  MyCFAdminGroup:
    Type: 'AWS::IAM::Group'
    Properties:
      GroupName: admin-team

  
  # Add User MyCFUser To User Group: MyCFUserGroup
  Users:
    Type: 'AWS::IAM::UserToGroupAddition'
    Properties:
      GroupName: !Ref MyCFUserGroup
      Users:
        - !Ref MyCFUser
  
  # Add User MyAdminUser To Group MyCFAdminGroup
  Admins:
    Type: 'AWS::IAM::UserToGroupAddition'
    Properties:
      GroupName: !Ref MyCFAdminGroup
      Users:
        - !Ref MyAdminUser
  
  
  # Add Policy To Group MyCFUserGroup
  MyCFUserPolicies:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: MyCFUsers
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - 'cloudformation:Describe*'
              - 'cloudformation:List*'
              - 'cloudformation:Get*'
            Resource: '*'
      Groups:
        - !Ref MyCFUserGroup
  
  # Add Policy To Group MyCFAdminGroup
  MyCFAdminPolicies:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: MyCFAdminPolicy
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action: '*'
            Resource: '*'
      Groups:
        - !Ref MyCFAdminGroup
  
  # Create an Access Key for our user
  MyCFUserKey:
    Type: 'AWS::IAM::AccessKey'
    Properties:
      UserName: !Ref MyCFUser

  # Create an Access Key for our MyAdminUser
  MyCFAdminKey:
    Type: 'AWS::IAM::AccessKey'
    Properties:
      UserName: !Ref MyAdminUser


# Template Output Section
Outputs:
  AccessKey:
    Value: !Ref MyCloudFormationKeys
    Description: AWSAccessKeyId of new user
  SecretKey:
    Value: !GetAtt 
      - MyCloudFormationKeys
      - SecretAccessKey
    Description: AWSSecretKey of new user


# Template Parameters Section
Parameters:

  # Enter your Username Here or choose an option
  Username:
    Type: String
    Default: eec-cloud-user
    AllowedValues:
      - eec-cloud-user
      - eec-docker-lab
      - eec-git-lab
      - eec-kb-lab
      - eec-jenkins-lab
      - eec-edureka-lab
    MinLength: '1'
    MaxLength: '41'
    Description: New account username

  # Enter Password here
  Password:
    NoEcho: 'true'
    Type: String
    Description: New account password
    MinLength: '1'
    MaxLength: '41'
    ConstraintDescription: the password must be between 1 and 41 characters



  # Enter your Username Here or choose an option
  AdminUsername:
    Type: String
    Default: eec-cloud-admin
    AllowedValues:
      - eec-cloud-admin
      - eec-docker-admin
      - eec-git-admin
      - eec-kb-admin
      - eec-jenkins-admin
      - eec-edureka-admin
    MinLength: '1'
    MaxLength: '41'
    Description: New account username

  # Enter Password here
  AdminPassword:
    NoEcho: 'true'
    Type: String
    Description: New account password
    MinLength: '1'
    MaxLength: '41'
    ConstraintDescription: the password must be between 1 and 41 characters



  

