---

Description: EC2 instance created by Emmanuel during CloudFormation Practice

# Resources to create
Resources:


  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-a4c7edb2
      AvailabilityZone: us-east-1a
      InstanceType:  t2.micro
      Tags: 
        - Key: Name
          Value: My-First-Template



# CloudFormation Parameters
Parameters:

# Type of instance
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.small
    AllowedValues:
      - t1.micro
      - t2.nano
      - t2.micro
      - t2.small
    ConstraintDescription: must be a valid EC2 instance type.
